---
title: "Anova Manova"
author: "Nzambuli Daniel"
date: "2024-01-29"
output: html_document
---

# Anova

Remember that

> -   For **Two Categorical Variables** use `chi-square test`
>
> -   For **Two numerical variables** use `t-test`

::: {style="background-color: #30c5ff;"}
**Assessing Normal Distribution**

Is a normal distribution curve gotten from `e` or $\hat{y}_i$

Thought process is from

$$
e_i = y_i - \hat{y}_i
$$ and $\hat{y}_i$ is found from a table

+-------+-------+
| x     | y     |
+=======+=======+
| $x_1$ | $y_1$ |
+-------+-------+
| $x_2$ | $y_2$ |
+-------+-------+
| .     | .     |
|       |       |
| .     | .     |
|       |       |
| .     | .     |
+-------+-------+
| $x_n$ | $y_n$ |
+-------+-------+

used to develop a linear regression equation such that

$$
\hat{y_i} = \beta_0 + \beta_1 x
$$

x is the initial constant from the table

**Conclusion**

notice that e is `a function of` y and $\hat{y_i}$

-   in a normal distribution the zero line is $\mu (e)$

-   the values up to `3 sd` are derived from e
:::

### Hypotheses

In two means tests the null hypothesis was

$$
\mu_1 = \mu_2
$$

Anova compare *t* population means where ***t\>2***.

The null hypothesis for variance of t population means is

$$
H_0 : \mu_1 = \mu_2 = ... = \mu_t
$$

The alternate hypothesis is : `atleast one mean is different from the rest`

### Test Statistic

The statistic `F` is the ratio between group sample variance and the within-group sample variance

$$
F = \frac{between group variance}{withing group variance}
$$

The aim is to make the `F-statistic` as close as possible to `1`

### Assumption for Anova

-   The response for each factor level have `normal population distribution`

$$
y_i\ is\ normally\ distributed
$$

-   The distributions have the `same variance` **homoscedasticity**

$$
\sigma^2\ is\ constant
$$

-   The data are `independent`

-   data have `common mean`

$$
\mu_1 = \mu_2 = ... = \mu_t
$$

## Anova Table

**Population/ groups/ Treatment**

-   The number of homogeneous groups

$$
1,\ 2,\ ...,t
$$

represented as `g`

**Data/ Subject**

-   The random samples of size $n_1,\ n_2,\ ..., \n_t$ are drawn from the `t` populations

-   $y_{i,j}$ The $j^{th}$ observation from the $i^{th}$ population

-   $n_i$ the sample size of the $i^{th}$ population

$$
n_T = \sum^t_{i = 1} n_i
$$

the total sample size

**Sample Means and General Mean**

-   $\bar{y_i}$ the mean of the sample in the $i^{th}$ population

-   $\bar{y_{..}}$ the general mean

## Examining Between Group Variation and Within Group Variation

### Sum of Squares for Treatment (Between Group Sum of Squares)

$$
SST = \sum^t_{i = 1} n_i(\bar{y_i} - \bar{y..})^2
$$

### Sum of Squares for Error(Within Group Sum of Squares)

$$
SSE = \sum_{i,j} (y_{ij} - \bar{y_{i.}})^2
$$

### Total Sum of Squares

$$
TSS = SST + SSE
$$

such that

$$
TSS = \sum_{i,j}(y_{ij} - \bar{y}_{..})^2
$$

## The Table

| source    | Df    | ss  | MS                        | F                 |
|-----------|-------|-----|---------------------------|-------------------|
| Treatment | g-1   | SST | $MST = \frac{SST}{g - 1}$ | $\frac{MST}{MSE}$ |
| Error     | N - g | SSE | $MSE = \frac{SSE}{N-g}$   |                   |
| Total     | N-1   |     |                           |                   |

# Manova

## Notion

-   $y_{ijk}$ observation for **variable k** from **subject j** in **group i**

$$
Y_{ij} = \begin{bmatrix}
y_{ij1}\\
y_{ij2}\\
\vdots\\
y_{ijp}
\end{bmatrix}
$$

which is a `vector of variables for subjects j in group i`

***i*** the `treatment`

-   The matrix has $n_i$ rows. **n** represents the number of `subjects` in a group

::: {style="background-color:#fa3bf0;"}
$$
N = n_1 + n_2 + ...+n_g
$$

Total **sample size**
:::

## Assumptions

1.  the data from group *i* has common mean vector

$$
\mu_i = \begin{bmatrix}
\mu_{i1}\\
\mu_{i2}\\
\vdots\\
\mu_{ip}
\end{bmatrix}
$$

-   data have common variance-covariance matrix $\Sigma$.

-   **Independence** independence in sampling of data

-   **Normality** multivariate normal distribution.

## Hypothesis

$H_0$ is the mean vector are equal to one another

$$
\mu_1 = \mu_2 =\ ...\ = \mu_g
$$

## Vectors

### sample mean vector

For group *i* with *p* variables

$$
\bar{y}_i = \frac{1}{n_i} \sum^{n_i}_{j=1}Y_{ij1} = \begin{bmatrix}
\bar{y}_{i1}\\
\bar{y}_{i2}\\
\vdots\\
\bar{y}_{ip}
\end{bmatrix}
$$

This is the same for variable **k** in group **i** is expressed as $Y_{ijk}$.

### Grand mean vector

The grand means for each of the *p* variables.

$$
\bar{y}_{..} = \frac{1}{N}\sum^{g}_{i=1}\sum^{n_i}_{j=1} Y_{ij} = \begin{bmatrix}
\bar{y}_{..1}\\
\bar{y}_{..2}\\
\vdots\\
\bar{y}_{..p}
\end{bmatrix}
$$

### Total Sum of Squares and Cross Products

::: {style="background-color: #1bfc06;"}
I didn't get this part
:::

To do further self reading [click here](https://www.bing.com/ck/a?!&&p=f369366dd4762f5eJmltdHM9MTcwNjQ4NjQwMCZpZ3VpZD0zODRkZTI4OS00NGQ1LTZlYmYtMWE2Mi1mMTJjNDUyOTZmODImaW5zaWQ9NTIwMg&ptn=3&ver=2&hsh=3&fclid=384de289-44d5-6ebf-1a62-f12c45296f82&psq=manova+tutorial&u=a1aHR0cHM6Ly9vbmxpbmUuc3RhdC5wc3UuZWR1L3N0YXQ1MDUvYm9vay9leHBvcnQvaHRtbC83NjI&ntb=1).
